project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  
website:
  title: "InsectOmics Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: labmembers.qmd
        text: Lab members
      - href: publications.qmd
        text: Publications
      - href: oppurtunities.qmd
        text: Opportunities
      - href: presentations.qmd
        text: Presentations
      - href: teaching.qmd
        text: Teaching
#      - href: contact.qmd
#        text: contact
#      - href: posts.qmd
#        text: blog

    right:
#    - text: "{{< ai google-scholar size=1x >}}"
#      aria-label: google-scholar
#      href: https://scholar.google.co.uk/citations?user=svTW0-wAAAAJ&hl=en
#    - text: "{{< ai orcid size=1x >}}"
#      aria-label: orcid
#      href: https://orcid.org/0000-0003-0811-8604
#    - icon: twitter
#      aria-label: twitter
#      href: https://twitter.com/saadarif8
#    - icon: github
#      aria-label: github
#      href: https://github.com/saadarif
    - icon: envelope  
      aria-label: email
      href: mailto:sarif@brookes.ac.uk
  
  page-footer: "Copyright 2024 &copy; Saad Arif"
  google-analytics: "G-0BT27VTKJN"
  site-url: https://saadarif.github.io
  repo-url: https://github.com/saadarif/saadarif.github.io
  
format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    #page-layout: full
    toc: true



