project:
  type: website
  output-dir: docs
  
website:
  title: "Saad Arif"
  navbar:
    left:
      - href: index.qmd
        text: home
      - research.qmd
      - teaching.qmd

format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    page-layout: full
    toc: true



