project:
  type: website
  output-dir: docs
  
website:
  title: "Saad Arif"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: Research.qmd
        text: research
      - href: Resources.qmd
        text: resources
      - href: Lab.qmd
        text: lab 
      - href: posts.qmd
        text: blog

    right:
    - text: "{{< ai google-scholar size=1x >}}"
      aria-label: google-scholar
      href: https://scholar.google.co.uk/citations?user=svTW0-wAAAAJ&hl=en
    - text: "{{< ai orcid size=1x >}}"
      aria-label: orcid
      href: https://orcid.org/0000-0003-0811-8604
    - icon: twitter
      aria-label: twitter
      href: https://twitter.com/saadarif8
    - icon: github
      aria-label: github
      href: https://github.com/saadarif
    - icon: envelope  
      aria-label: email
      href: mailto:sarif@brookes.ac.uk

format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    #page-layout: full
    toc: true



