---
title: "Evidence for multiple colonisations and Wolbachia infections shaping the genetic structure of the widespread butterfly <em>Polyommatus icarus</em> in the British Isles"
type: "article"
author: "Arif, Hone-Millard, Gerth, et al."
year: "2021"
publication: "Molecular Ecology"
preprint: "https://doi.org/10.1101/2020.09.03.267203"
doi: " https://doi.org/10.1111/mec.16126"
materials: "https://github.com/saadarif/CommonBlue-UKPhylogeography"
toc: false
categories:
  - butterflies
  - phylogeography
  - popualtion genomics
  - wolbachia
  - student publication
---

## Citation

> Arif, S., Gerth, M., Hone-Millard, W. G., Nunes, M. D. S., Dapporto, L., & Shreeve, T. G. (2021). Evidence for multiple colonisations and Wolbachia infections shaping the genetic structure of the widespread butterfly *Polyommatus icarus* in the British Isles. Molecular Ecology, 30(20), 5196–5213. https://doi.org/10.1111/mec.16126

## Abstract

The paradigm of isolation in southern refugia during glacial periods followed by expansions during interglacials, producing limited genetic differentiation in northern areas, dominates European phylogeography. However, the existence of complex structured populations in formerly glaciated areas, and islands connected to mainland areas during glacial maxima, call for alternative explanations. We reconstructed the mtDNA phylogeography of the widespread Polyommatus Icarus butterfly with an emphasis on the formerly glaciated and connected British Isles. We found distinct geographical structuring of CO1 haplogroups, with an ancient lineage restricted to the marginal European areas, including Northern Scotland and Outer Hebrides. Population genomic analyses, using ddRADSeq genomic markers, also reveal substantial genetic structuring within Britain. However, there is negligble mito-nuclear concordance consistent with independent demographic histories of mitochondrial versus nuclear DNA. While mtDNA-Wolbachia associations in northern Britain could account for the geographic structuring of mtDNA across most of the British Isles, for nuclear DNA markers (derived from ddRADseq data) butterflies from France cluster between northern and southern British populations – an observation consistent with a scenario of multiple recolonisation. Taken together our results suggest that contemporary mtDNA structuring in the British Isles (and potentially elsewhere in Europe) largely results from Wolbachia infections, however, nuclear genomic structuring suggests a history of at least two distinct colonisations. This two-stage colonisation scenario has previously been put forth to explain genetic diversity and structuring in other British flora and fauna. Additionally, we also present preliminary evidence for potential Wolbachia-induced feminization in the Outer Hebrides.
