---
title: "Evolution of Eye Morphology and Rhodopsin Expression in the <em>Drosophila melanogaster</em> Species Subgroup"
type: "article"
author: "Posnien, Hopfen, Hilbrant, et al."
year: "2012"
publication: "PLoS ONE"
preprint: ""
doi: "https://doi.org/10.1371/journal.pone.0037346"
github: ""
toc: false
categories:
  - drosophila
  - geometric morphometrics
  - evo-devo
  - compound eyes
  
---

## Citation

> Posnien, N., Hopfen, C., Hilbrant, M., Ramos-Womack, M., Murat, S., Schönauer, A., Herbert, S. L., Nunes, M. D. S., Arif, S., Breuker, C. J., Schlötterer, C., Mitteroecker, P., & McGregor, A. P. (2012). Evolution of Eye Morphology and Rhodopsin Expression in the Drosophila melanogaster Species Subgroup. PLOS ONE, 7(5), e37346. https://doi.org/10.1371/journal.pone.0037346


## Abstract

A striking diversity of compound eye size and shape has evolved among insects. The number of ommatidia and their size are major determinants of the visual sensitivity and acuity of the compound eye. Each ommatidium is composed of eight photoreceptor cells that facilitate the discrimination of different colours via the expression of various light sensitive Rhodopsin proteins. It follows that variation in eye size, shape, and opsin composition is likely to directly influence vision. We analyzed variation in these three traits in D. melanogaster, D. simulans and D. mauritiana. We show that D. mauritiana generally has larger eyes than its sibling species, which is due to a combination of larger ommatidia and more ommatidia. In addition, intra- and inter-specific differences in eye size among D. simulans and D. melanogaster strains are mainly caused by variation in ommatidia number. By applying a geometric morphometrics approach to assess whether the formation of larger eyes influences other parts of the head capsule, we found that an increase in eye size is associated with a reduction in the adjacent face cuticle. Our shape analysis also demonstrates that D. mauritiana eyes are specifically enlarged in the dorsal region. Intriguingly, this dorsal enlargement is associated with enhanced expression of rhodopsin 3 in D. mauritiana. In summary, our data suggests that the morphology and functional properties of the compound eyes vary considerably within and among these closely related Drosophila species and may be part of coordinated morphological changes affecting the head capsule.