---
title: "Heterochrony in orthodenticle expression is associated with ommatidial size variation between <em>Drosophila</em> species"
type: "article"
author: "Torres-Olivia, Buchberger, Buffry, et al."
year: "2025"
publication: "BMC Biology"
preprint: "https://doi.org/10.1101/2021.03.17.435774"
doi: "https://doi.org/10.1186/s12915-025-02136-8"
github: ""
toc: false
categories:
  - drosophila
  - transcriptomics
  - evo-devo

---

## Citation

>Torres-Oliva, M., Buchberger, E., Buffry, A.D. et al. Heterochrony in orthodenticle expression is associated with ommatidial size variation between Drosophila species. *BMC Biol* *23**, 34 (2025). https://doi.org/10.1186/s12915-025-02136-8


## Abstract

**Background**
The compound eyes of insects exhibit extensive variation in ommatidia number and size, which affects how they see and underlies adaptations in their vision to different environments and lifestyles. However, very little is known about the genetic and developmental bases of differences in eye size. We previously showed that the larger eyes of *Drosophila mauritiana* compared to *D. simulans* are generally caused by differences in ommatidia size rather than number. Furthermore, we identified an X-linked chromosomal region in *D. mauritiana* that results in larger eyes when introgressed into *D. simulans*.

**Results**
Here, we used a combination of fine-scale mapping and gene expression analysis to further investigate positional candidate genes on the X chromosome. We found earlier expression of orthodenticle (otd) during ommatidial maturation in *D. mauritiana* than in *D. simulans*, and we show that this gene is required for the correct organisation and size of ommatidia in *D. melanogaster*. We discovered that the activity of an otd eye enhancer is consistent with the difference in the expression of this gene between species, with the *D. mauritiana* enhancer sequence driving earlier expression than that of *D. simulans*. When otd expression is driven prematurely during *D. melanogaster* eye development, the ommatidia grow larger, supporting a possible role for the timing of otd expression in regulating ommatidial size. We also identified potential direct targets of Otd that are differentially expressed between *D. mauritiana* and *D. simulans* during ommatidial maturation.

**Conclusions**
Taken together, our results suggest that differential timing of otd expression may contribute to natural variation in ommatidia size between *D. mauritiana* and *D. simulans*, which provides new insights into the mechanisms underlying the regulation and evolution of compound eye size in insects.